# Generated by Django 4.2.7 on 2023-12-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('Loc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('Grade', models.IntegerField(primary_key=True, serialize=False)),
                ('Losal', models.IntegerField()),
                ('Hisal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('Mgr', models.IntegerField()),
                ('Hiredate', models.DateField()),
                ('com', models.IntegerField()),
                ('Dept_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
